---
info:
  version: 1.0.0
  description: Middleware application for OAI 5GCN Orchestration

configuration:
  nbi:
    nbi1:
      name: magma 
      networkId: oai
      gatewayId: oaigw1
      generatehwId: false
      hardwareId: 22ffea10-7fc4-4427-975a-b9e4ce8f6f4d
      cloudAddress: controller.magma.test
      cloudStreamerPort: 8443
      cloudHttpsPort: 9443
      streamInterval: 5
      registerGateway: false

  sbi:
    enableReporting: false
    enableHttp2: false
    services:
      - name: oai-amf
        address: 192.168.70.132
        port: 80
      - name: oai-smf
        address: 192.168.70.133
        port: 80
      - name: oai-upf
        address: 192.168.70.134
        port: 80
      - name: oai-udr
        address: 192.168.70.136
        port: 80
        
logger:
  logLevel: info 
